[tool.poetry]
name = "train-xgb-package"
version = "0.1.0"
description = ""
authors = ["ariadnafer <ariadna.fernandez@datatonic.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "3.7.9"
pandas = "^1.1"
numpy = "^1.20"
scikit-learn = "0.24"
xgboost = "^1.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
